### ISSUE TITLE
[Silent Hill 2] Red-tinted FMVs w/ IGPU & Shader Oddity

### ISSUE THREAD

**Issue by jdkubiak** [crosire/d3d8to9#24]
Hello, 

With using ThirteenAG/Aero52's [Silent Hill 2 Widescreen Fix](https://thirteenag.github.io/wfp#sh2) and activating the d3d8to9 feature I've noticed two visual oddities that come up: 

If using integrated graphics all of the FMV cutscenes will be tinted completely red: 

![untitled](https://cloud.githubusercontent.com/assets/27395260/26419217/e687c3ea-408c-11e7-9ef9-34eb566a81de.png)

And in one of the in-game cutscenes the lighting/shaders on James' body is cranked up too much (this happens using Nvidia, AMD, or integrated graphics): 

![f3435fe0-400a-11e7-8ecd-a5f1f81abda1](https://cloud.githubusercontent.com/assets/27395260/26419008/4f57f666-408c-11e7-9c5d-8d434d5b6640.jpg)
![f3458950-400a-11e7-9726-44546687e718](https://cloud.githubusercontent.com/assets/27395260/26419009/4f5945de-408c-11e7-8aac-21df9c105690.jpg)

I intend to do a speedrun playthrough soon of the game to see if there are any other spots that have been affected by the lighting issue when d3d8to9 is enabled. 

I'm not sure if this is within the ballpark of fixes for ReShade but would like to address them for posterity. 

Thank you

**Comment by CookiePLMonster** [comment]
According to this post, these issues may be fixed now (with a new widescreen fix):
http://gtaforums.com/topic/547841-gtanfsmpother-widescreen-fixes-pack/?p=1069610259

**Comment by Aero52** [comment]
The issue we fixed was something else that was causing people to crash and other defects. 

There's some odd flashlight problems that occur, and I guess the severity of them depends on the type of GPU you're using. I only have a weird issue where all of the NPCs illuminate for a few seconds after turning on the flashlight.

All that's necessary to reproduce this is Ultimate ASI Loader renamed to d3d8.dll, and global.ini in the scripts folder with the below settings:

> [GlobalSets]
LoadPlugins=1
LoadFromScriptsOnly=1
ForceEntryPointHook=1
UseD3D8to9=1

**Comment by elishacloud** [comment]
I am not sure if this is related to the issue reported about incorrect lighting and a red tint in the movies but I am getting a "Failed to reassemble shader" error from `CreateVertexShader`.

Here is the shader after immediately after disassembly:
```text
22964 15:04:48.512 > Dumping translated shader assembly:
    vs_1_1
    dp4 oPos.x, v0, c0
    dp4 oPos.y, v0, c1
    dp4 oPos.z, v0, c2
    dp4 oPos.w, v0, c3
    mov oD0, c14.w
    mov oFog.x, c14.x
    mov oT0, c14.x
    mov oT1, c14.x
    mov oT2, c14.x
    mov oT3, c14.x

// approximately 10 instruction slots used
```
And here is the shader right before reassembly:
```text
22964 15:04:48.512 > Dumping translated shader assembly:
    vs_1_1
    dcl_position v0
    mov oT3, c0 /* initialize output register oT3 */
    mov oT2, c0 /* initialize output register oT2 */
    mov oT1, c0 /* initialize output register oT1 */
    mov oT0, c0 /* initialize output register oT0 */
    mov oD0, c0 /* initialize output register oD0 */
    dp4 oPos.x, v0, c0
    dp4 oPos.y, v0, c1
    dp4 oPos.z, v0, c2
    dp4 oPos.w, v0, c3
    mov oD0, c14.w
    mov oFog /* removed swizzle */, c1.x /* select single component */4.x
    mov oT0, c14.x
    mov oT1, c14.x
    mov oT2, c14.x
    mov oT3, c14.x

// approximately 10 instruction slots used

22964 15:04:48.512 > CreateVertexShader: Failed to reassemble shader:
D:\Games\Silent Hill 2\memory(13,71): error X2000: syntax error : unexpected float '4'
```
Notice the line:
```text
    mov oFog /* removed swizzle */, c1.x /* select single component */4.x
```
It seems to have incorrectly changed `c14.x` to `c1.x /* select single component */4.x`.  This issue also appears to be in [this](https://github.com/crosire/d3d8to9/blob/master/source/d3d8to9_device.cpp#L1392) line of code and looks like the same issue reported in issue [#28](https://github.com/crosire/d3d8to9/issues/28).

**Comment by elishacloud** [comment]
I cannot seem to reproduce the lighting and red tint issue.  The video and lighting seem ok for me.  Maybe it is because I am using an nVidia GTX 790 video card.

However, after looking at the [source code](https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SilentHill2.WidescreenFix/dllmain.cpp) for the WidescreenFixes it looks like the lighting problem may be related to the `LightingFix` setting in the "SilentHill2.WidescreenFix.ini" file.

It appears that the [LightingFix](https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SilentHill2.WidescreenFix/dllmain.cpp#L444) modifies the memory of the process, which seem risky to me and may work differently on Direct3D8 vs Direct3D9.  I recommend disabling the `LightingFix` feature and see of the problem goes away.

In the "scripts\SilentHill2.WidescreenFix.ini" file change:
```ini
LightingFix = 1
```
To:
```ini
LightingFix = 0
```

**Comment by jdkubiak** [comment]
Hi Elisha, 

Thanks for responding. Did you test that same particular cutscene for the lighting bug? I ask because, as far as I can tell so far, that's the only cutscene/area that is affected by this. But this is also one of the most pivotal cutscenes in the game so having that bug there especially is no fun. 

I've disabled the "LightingFix" within the SH2 Widescreen Fix and the bug still happens. 

It seems to be something within ReShade as I tried an older version of ReShade (from 1+ years ago) and the bug does not happen. My guess is as the code for ReShade evolved it changed something enough to affect this game. 

I can't say for certain if this only affects certain video cards but am leaning on not because it affected Nvidia, AMD, and integrated graphics cards in my tests. 

The red-tinted FMVs will only be visible on integrated graphics; Nvidia and AMD cards seem to be fine with that particular bug.

**Comment by elishacloud** [comment]
I am wondering if the lighting issue is the same one mentioned in [#28](https://github.com/crosire/d3d8to9/issues/28).  Can you check [this](https://github.com/crosire/d3d8to9/files/1118465/d3d8.zip) file and let me know if this solves the lighting issue.

Note: the red tint issue is something else.  That needs to be looked at separately.

**Comment by jdkubiak** [comment]
Hi Elisha, 

I'm sorry for the delay but I'm very happy to say that fixed the problem! Thank you for your time and ingeniousness! 

May I ask one last request? I don't know if this should be asked at all; asked here; or made into a new ticket; but [WineD3D For Windows](http://fdossena.com/?p=wined3d/index.frag) (using its D3D9 version/files) seems to be incompatible with ReShade's D3D8to9 and Silent Hill 2. 

Could this possibly be looked in to? WineD3D For Windows is crucial to use for this game as it fixes many visual eye sores that Nvidia cards produce for this game. A video example of some of these issues in action: 

https://www.youtube.com/watch?v=878F2cbLAXo

When used with ReShade's converter the game simply hangs on launch. So for now, I've been using/telling others to use the ENB Converter in an [installation guide](http://widescreenfix.townofsilenthill.com/SH2/) I've made. Although I'd love to consolidate these steps and using Widescreen Fix's built-in ReShade D3D8to9 converter instead of the ENB Converter for WineD3D For Windows, if that's possible.

**Comment by elishacloud** [comment]
Thanks for the follow up.  I am glad that this fixed the lighting issue.  Basically there were three issues I found:
1. Dangling Swizzles.

For this I added `[\\.wxyz]*(?![\\.wxyz])` in the regex to ensure that it always matched on all swizzles.  This line [here](https://github.com/crosire/d3d8to9/blob/678951ec7e1e3e0a9e38e40e2025164298e1aab1/source/d3d8to9_device.cpp#L1733) was change to this:
```c++
SourceCode = std::regex_replace(SourceCode, std::regex("(1?-)(c[0-9][\\.wxyz]*(?![\\.wxyz]))"), "$2 /* removed modifier $1 */");
```
2. d3d8to9 removed the `-` modifier on an `add` arithmetic function.

I fixed this by changing the `add` to a `sub` by adding this line here:
```c++
SourceCode = std::regex_replace(SourceCode, std::regex("(add)([_satxd24]*) (r[0-9][\\.wxyz]*), ((1-|)[crtv][0-9][\\.wxyz_abdis2]*), (-)(c[0-9][\\.wxyz]*)(_bx2|_bias|_x2|_d[zbwa]|)(?![_\\.wxyz])"), "sub$2 $3, $4, $7$8 /* changed 'add' to 'sub' removed modifier $6 */");
```
3.  d3d8to9 removed the `_bx2` modifier.

This was a harder fix and there is no perfect solution.  For Silent Hill 2 the `_bx2` modifier was used on all source registers.  So after doing some math I believe that removing both `_bx2` source registers and adding the `_x2` modifier to the arithmetic function would get a closer result to what was intended.

I made this change by adding this line:
```c++
SourceCode = std::regex_replace(SourceCode, std::regex("((?![ ])...)(_sat|) (r[0-9][\\.wxyz]*), ([crtv][0-9][\\.wxyz]*)_bx2, (c[0-9][\\.wxyz]*)_bx2(?!,)"), "$1_x2$2 $3, $4, $5 /* removed modifiers _bx2 added modifier _x2 */");
```

The patch above only has the first two fixes in it.  The third fix also seems to improve the lighting (at least I noticed it looked better).  [Here](https://github.com/crosire/d3d8to9/files/1122922/d3d8.zip) is an updated file with all three fixes.

As far as the red tint issue and the WineD3D issues they will need to be looked at separately.  This fix so far only fixes the lighting issue.

**Comment by jdkubiak** [comment]
So, um, won't lie; what you just said is 100% Greek to me. Nonetheless I'm amazed and astounded you could problem solve this issue with the coding language you shared above. 

Would you imagine ReShade's D3D8to9 would be compatible to work with WineD3D For Windows' D3D9 file(s) in the future as well?

**Comment by elishacloud** [comment]
Well, I am not the owner of this project and cannot make any promises.  But I will take a look at the WineD3D issue when I have time and see if I can figure out what the issue is.

**Comment by elishacloud** [comment]
I did some testing on the WineD3D issue.  Checkout this update [here](https://github.com/crosire/d3d8to9/files/1132009/d3d8.zip) and let me know how this works.

**Comment by jdkubiak** [comment]
Unfortunately it still hangs the game on launch (requiring a force quit) when used with WineD3D For Windows. I tested this on a Win7 64 bit machine, if that matters/helps.

**Comment by elishacloud** [comment]
I have seen this before.  but I am not sure it is actually freezing.  It just takes several minutes to start up.  Have you tried waiting longer?  I have seen it take as long as 4 minutes.  This happened once on my computer but now it no longer happens.  It took about 1 minute the first time.  Let me see if I can reproduce this on Windows 7.

**Comment by jdkubiak** [comment]
You totally hit the nail on the head: Letting it sit for about 2-3 minutes launched the game afterwards. The only thing is the "loading" time stayed the same upon me launching the game four different times. Not the most ideal scenario. Any hunch as to why it hangs up for so long?

**Comment by elishacloud** [comment]
I still cannot really reproduce this issue on either of my computers.  But on one system it took around 20 seconds to load the game.

Also, I found an issue with the way d3d8to9 handles `GetAdapterModeCount` and `EnumAdapterModes`.  Each time the game calls these APIs d3d8to9 calls thousands of Direct3D9 APIs.  This happens several times at the beginning of Silent Hill 2.

The ENB Converter handles this by caching the results of the API on the first run and then using that cache the rest of the time.  I tried the same thing with d3d8to9 and it decrease the loading time on my system down to around 2 seconds.  Let me know how [this](https://github.com/crosire/d3d8to9/files/1132928/d3d8.zip) one works for you.

**Comment by HerMajestyDrMona** [comment]
Slow loading time might be caused by a running Antivirus. I had a similar problems when I was testing Indiana Jones game. Bitdefender Total Security Active Threat Control was causing those issues, and sometimes was even crashing game on start. It usually isn't d3d8to9 nor WineD3D problem, but third party software that is running on system. I would recommend to test how it behaves with all programs disabled / some services stopped.

**Comment by jdkubiak** [comment]
That's the ticket Elisha!!! 

Loads within a small handful of seconds now! Damn you guys are so damn smart/impressive with all of this! 

@elishacloud do you have a PayPal/donation address I can send a small thank you tip to? 

Should there be no issues/concerns with caching the API results for ReShade as a broad update for the project? GitHub's site/interfaces are still fairly foreign to me but if/when @crosire implements these changes how would one know/be notified of the newest, public release for this?

**Comment by elishacloud** [comment]
Great!  I am glad this worked for you.  I have created an updated pull request [here](https://github.com/crosire/d3d8to9/pull/33).  When this pull request has been merged into the project I will make sure this thread is updated.

BTW: I don't need any donations.  One of my hobbies is getting older games to work on newer OS's.  Checkout my project [here](https://github.com/elishacloud/dxwrapper).  Also, I am using this project to learn Direct3D and C++.  I am learning a lot by all these issues.  :)

**Comment by elishacloud** [comment]
jdkubiak, the WineD3D code fix has just been [merged](https://github.com/crosire/d3d8to9/pull/33) in the project.  The only item left on this thread is the rd tint issue with the video.  I did notice that there is no red tint when using the WineD3D dll's.

**Comment by jdkubiak** [comment]
Sorry again for the delay; busy, busy week at work. 

So you're the creator of DxWrapper! Cool!! Thank you for everything you've done both here and for your own project. :) 

And thank you more so for helping the Silent Hill community as you've done. I love the fact you love doing this to better your skill set; your ambition is equal parts admirable and awesome! 

@ThirteenAG 's [Ultimate ASI Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases) (UAL) uses a built-in version of ReShade's D3D8to9 converter that can be switched on and off. So continuing on with my ignorance to how GitHub works: Can I direct ThirteenAG's attention to the merger you specified as the updated source code for him to use in his UAL?

**Comment by crosire** [comment]
@jdkubiak No, I have to update that download manually, which hasn't happened yet. I guess it would make sense to make use of https://github.com/crosire/d3d8to9/releases instead though and use a build server to automatically compile the DLL on every source code modification.

**Comment by elishacloud** [comment]
You can have @ThirteenAG just pick up the [latest code](https://github.com/crosire/d3d8to9/tree/ec883cee87bdc99cfcd5c6248e2db5ad644f6f0c) from this repository and add it to his [Ultimate ASI Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases) project.  Then once he makes a new release it will have all the changes needed for Silent Hill 2.

**Comment by ThirteenAG** [comment]
I'll update submodule a bit later, no need to worry about that.

**Comment by jdkubiak** [comment]
@elishacloud May I ask for your expertise once more?  

There's a flashlight bug that has popped up in the game now when using ReShade in conjunction with [WineD3D For Windows](https://fdossena.com/?p=wined3d/index.frag)' D3D9 files. Please see the video below: 

https://youtu.be/6fGhMyrs5mY 

WineD3D For Windows is a crucial package for fixing visual bugs for Nvidia users in the game and practically must be used as a result. As mentioned in the video, this issue doesn't occur when using ENB Converter + WineD3D For Windows so I'm thinking (hoping) an adjustment in ReShade would fix it the same? 

Some possibly important back story about the flashlight and this game: The flashlight in the vanilla version of this game was inherently bugged. When on, it would ALWAYS illuminate NPCs/items behind James. The only way to fix this back-in-the-day was to disable vertex shaders but doing so compromised the flashlight's visual quality drastically in the process. 

[Aero_](https://github.com/AeroWidescreen) from the [Widescreen Fix](https://thirteenag.github.io/wfp#sh2) projects made a fix to this bug that also retains vertex shading (thus preserving the flashlight's beautiful per pixel lighting). 

Any thoughts on the matter? 

This bug has also been reported by another user: 
https://github.com/ThirteenAG/WidescreenFixesPack/issues?q=is%3Aissue+is%3Aclosed

**Comment by elishacloud** [comment]
@jdkubiak, Ok, I will look into this.  Though it may be a little while before I will have a chance to work on this.

It would be great if you could get a link to change that [Aero_](https://github.com/AeroWidescreen) made that fixed this.

Also can you could tell me exactly how to get to that location in the game?

**Comment by AeroWidescreen** [comment]
@elishacloud All we did was add 00000010 to a few pointers. I don't think this is the same problem, but I'm no expert on any of this. Use LightingFix = 0 to disable it if you're using the widescreen fix.

https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SilentHill2.WidescreenFix/dllmain.cpp#L453-L456

The two memory addresses in the comments are for the no-cd v1.1 "gimpsRus" exe.

**Comment by jdkubiak** [comment]
Thank you for looking into this once more @elishacloud !

`Also can you could tell me exactly how to get to that location in the game?`

Absolutely! Download this save folder for the game: 

> http://www.igotaletter.com/temp/sh2pc/Maria_Ending.zip 

Copy "Folder 1" from the archive to the "\data\save" folder in your game's directory. 
Load up the game and choose the first save labeled "Hospital" from the list.

**Comment by elishacloud** [comment]
Thanks!  I was able to reproduce the problem.

**Comment by elishacloud** [comment]
Ok, I think I figured out the issue.  This looks like it might be a bug in Silent Hill 2 and not in d3d8to9.  Try [this](https://github.com/crosire/d3d8to9/files/1224062/d3d8.zip) one and let me know how it works.

This is a pretty bad hack.  I literally hard coded the pixel shaders in this one.  I will see if I can find a better fix for this later.

**Comment by elishacloud** [comment]
Well, it looks like I spoke too soon.  I found the issue with d3d8to9.  It was a pixel shader change I made [#32](https://github.com/crosire/d3d8to9/pull/32/commits/5d3fb1a53c001e883067c0dcc0bfab90168d442e#diff-366bc9823b5fedd9a67231f1896c4f8fR1767) to fix lighting issues.  I guess I was a bit over zealous in that change.

This updated d3d8to9 file [here](https://github.com/crosire/d3d8to9/files/1224100/d3d8.zip) should fix the issue properly.  I will add a pull request for this.

As far as the soft shadows I think that is a bit beyond what I could do.  I was primarily able to fix this since there was a working version and I could reverse it to figure out what was wrong.  Building something new like this is still a bit beyond me.  I might look into it when I have some free time.  But don't expect anything soon.

**Comment by crosire** [comment]
Closing this issue since the original bug was fixed a while ago.

**Comment by jdkubiak** [comment]
Thank you all for your wonderful support.

**Comment by jdkubiak** [comment]
Oh, and sorry for the delay on this @elishacloud --just got back home--but your second-revised .dll from last night also worked like a charm. :)

**Comment by AeroWidescreen** [comment]
> Very excited to see it cleaned up/optimized to your standards. With this and @AeroWidescreen working on a better noise filter for the game SH2 PC is now 99% perfect.

Yup, we're almost there. We just need to replace the audio and fix that annoying map problem. Thanks for email by the way, always appreciated.

> As far as the soft shadows I think that is a bit beyond what I could do. I was primarily able to fix this since there was a working version and I could reverse it to figure out what was wrong. Building something new like that is still a bit beyond me. I might look into it when I have some free time. But don't expect anything soon.
Maybe looking at SH3 could help? It has soft shadows, and I believe it uses the same engine.

**Comment by jdkubiak** [comment]
I feel confident some confidante will come out of the shadows with an audio fix for the game in time. That was certainly seems doable if we can just get started in the right direction. 

While no one prefers stretched images I personally am not all that bothered by them in order to fix the map issue. Although just like you I'd love and hope a solution shows it's head for it one day.

Does SH3 PC run on DirectX 8 like SH2 PC or is it on DirectX 9? If 9 that could explain how they got soft shadows. I also know SH3 is very clever in that it uses cel shaders to make it's shadow effects with very impressive results (for it's time).

**Comment by AeroWidescreen** [comment]
> While no one prefers stretched images I personally am not all that bothered by them in order to fix the map issue. Although just like you I'd love and hope a solution shows it's head for it one day.

There is one possible way I haven't tried yet but it's very hackish. I'd basically replace the game's zoom function with my own. You know how we change the width of the map to maintain its aspect ratio, which is what causes the black bars? I'd use that same method to scale the map larger when zoom is activated. It's all theoretical at the moment, so don't get your hopes up, but I'll try this weekend. 

> Does SH3 PC run on DirectX 8 like SH2 PC or is it on DirectX 9? If 9 that could explain how they got soft shadows. I also know SH3 is very clever in that it uses cel shaders to make its shadow effects with very impressive results (for its time).

It uses d3d8.dll just like SH2, that's as much as I know.

**Comment by jdkubiak** [comment]
> It uses d3d8.dll just like SH2, that's as much as I know.

That's good to hear! (Haven't been home to check myself.) There's always that small sliver of hope for the future, then. :)

**Comment by elishacloud** [comment]
@jdkubiak, what is the audio issue with Silent Hill 2?  Also can you explain the soft shadows request in bit more detail?

@AeroWidescreen, How did you create soft shadows in Silent Hill 3?

**Comment by AeroWidescreen** [comment]
@elishacloud I didn't create soft shadows in SH3. It already exists in the vanilla game. I was suggesting that maybe you could learn how that works and apply the same method to SH2. Sorry, I must've confused you with the shadow resolution stuff. I'm just saying my own shadow related research hasn't led me to anything in SH2.

@jdkubiak You're too quick. It would only apply to the map when you pressed a button to zoom in, just like it normally does, but the way the zoom is achieved would be different to avoid the pillarboxing. I edited my post so we can keep the discussion focused on soft shadows.

**Comment by jdkubiak** [comment]
> what is the audio issue with Silent Hill 2? Also can you explain the soft shadows request in bit more detail?

I'd be happy to! First, when you have a spare 25 minutes I'd strongly recommend watching this video that breaks down the difference between the main releases of SH2 for varios platforms: 
https://www.youtube.com/watch?v=nna2yt1c9gI 

**In regards to the audio:**
All versions of SH2 except for the PS2 version have compressed the audio files into a lossy format. This is further explained here: 
https://www.youtube.com/embed/nna2yt1c9gI?start=403&end=437

And while this situation is less than ideal the _tone and pitches_ for the audio files have also changed during the conversion. You can hear this in action here: 
https://www.youtube.com/watch?v=8E5Nt8ahZRk&t=2s

So while typically only audiophiles will be able to hear the reduced bitrate of the compressed audio files _everyone_ can pick up on these tone/pitch differences. It's equal parts strange and silly this happened. 

**In regards to the shadows:**
Both the PS2 and Xbox versions of the game utilize soft shadows in the game's world whereas the PC version uses simple, hard edge volumes which results in razor-sharp shadow lines. This reduction in shadow quality not only looks less than desirable but also hurts the game's atmosphere. 

You can learn more about the PC's shadows vs. consoles here: 
https://www.youtube.com/embed/nna2yt1c9gI?start=818&end=869

And in the same video they discuss more about the soft shadows being used in the PS2/Xbox versions here: 
https://www.youtube.com/embed/nna2yt1c9gI?start=353&end=404

And here: 
https://www.youtube.com/embed/nna2yt1c9gI?start=701&end=722

**Comment by jdkubiak** [comment]
@elishacloud this post is just backstory/context to give a better understanding of why so many fans are passionate in seeing SH2 PC fixed as a whole. Not required reading by any means:

Konami (the game's publisher) has become [infamous for grossly mistreating its IP](https://www.polygon.com/2015/12/16/10220356/hideo-kojima-konami-explainer-metal-gear-solid-silent-hills) and Silent Hill is no exception. SH2 has never (and probably will never) receive a proper HD remaster/remake. You may have heard of the "Silent Hill HD Collection" for PS3/Xbox 360 which contains SH2 and SH3 being "remastered" but it's anything but... 

Keeping in tradition with mishandling their IP Konami's first mistake was giving the task of remastering two of their most beloved titles to Hijinx Studios. Hijinx's [previous work](https://www.giantbomb.com/hijinx-studios-llc/3010-6317/) includes Karaoke Revolution, TouchMaster, and Frogger Returns. So not only have they ever developed shovelware style games but they have never remastered a game before (as opposed to a studio such as BluePoint Games who is known for their masterful work at [reverse engineering](https://www.engadget.com/2011/09/23/bluepoint-games-offers-insight-into-mgs-ico-god-of-war-remake/) old games to remaster them). 

Konami's second mistake--and boy this one is a doozy--is that they _[lost the master source code for SH2](http://www.eurogamer.net/articles/2012-05-29-silent-hill-hd-collection-ported-from-unfinished-code)_ so Hijinx Studio received _beta code_ of SH2 to work with. 

Needless to say, when the "Silent Hill HD Collection" shipped it was riddled with [bugs, glitches, errors, and so, so much more](http://silenthillcommunity.com/viewtopic.php?p=7587759&sid=e43e4b65e73267364f67af8c72f03ab6#p7587759). They inexplicably changed the voice actors for SH2 (with the majority agreeing for the worse) and their attempt and remaking the textures range from [a muddied mess](http://www.neogaf.com/forum/showthread.php?t=467571) to [THE cardinal sin of graphic design](https://www.youtube.com/watch?v=XqJ2EA0DTP8). 

So "Silent Hill HD Collection" is out of the question then to experience SH2 in HD. That leaves us with emulating the PS2 game or enhancing the PC version of the game. 

Emulating is certainly a viable option but it is also a very extensive and involved process. From having to [extract your own PS2 BIOS](http://forums.pcsx2.net/Thread-Guide-to-Dumping-Your-PS2-Bios-over-LAN) to modifying many settings to get the game to run properly (and even then there [have been reported issues](http://forums.pcsx2.net/search.php?action=results&sid=b8715652fcd13cde91dcd6f5b3a29be5&sortby=&order=desc)) to having a powerful, stout PC to run PCSX2/SH2 without lag this option leaves the Average Joe out of luck to play this game in HD. 

That leaves us with the most logical option: Fixing and modifying SH2 PC to get the game up to modern standards. 

Unfortunately, the vanilla PC version of the game is inferior to its console brethren (especially the PS2 version which I'll get to in a moment) in numerous ways. But we can consolidate the main issues as such: 

- Lack of a widescreen camera
- Various audio/visual bugs
- Lackluster fog effect
- Inferior noise grain filter
- Compressed, lossy audio 
- Compressed, lossy FMVs
- Sharp shadows

But @ThirteenAG and @AeroWidescreen  , with the help of other brilliant minds (include you!), have been doing a _fantastic_, wonderful job addressing many of these issues. Let's go back to the list of issues:

- Lack of a widescreen camera
**Fixed** via Widescreen Fix.
- Various audio/visual bugs
**Fixed** via Widescreen Fix, ReShade D3D8to9, and WineD3D For Windows.
- Lackluster fog effect
**Fixed** via the [Fog Fix](http://ps2wide.net/pc.html#sh2).
- Inferior noise grain filter
**[In progress](https://github.com/ThirteenAG/WidescreenFixesPack/issues/304#issuecomment-321802522)** of being fixed via Widescreen Fix.
- Compressed, lossy audio 
**No** solution found.
- Compressed, lossy FMVs
**Fixed** via [Enhanced FMV Package](https://www.youtube.com/watch?v=nna2yt1c9gI&feature=youtu.be&t=9m15s).
- Sharp shadows
**No** solution found. 

With the insurmountable work and progress done by these fine people the PC version is _this_ close to becoming not only up to standards to its PS2 counterpart, but also surpassing it in many ways with the HD/widescreen enhancements to go along with it. 

After being mistreated and figuratively abused by its owner (Konami) for 1.5 decades Silent Hill 2 fans--including myself--have become starry-eyed over the thought of seeing this masterpiece brought up to modern gaming standards. Most households no longer have CRT TVs so playing the game on a PS2 or original Xbox will look awful on these newfangled TVs. Many households don't have high ends PCs so emulating the game is out of the question (plus the immense legwork that the average person would have to do to get it running). And the Silent Hill HD Collection... well... we don't talk about that.

**Comment by mirh** [comment]
Dumping PS2 bios is rock easy once you have an hacked memory card (even better if it's one of those USB-compatible)
Also dumping PS2 assets isn't all that sci-fi in many games afaik. Sometimes you don't even need coding at all because the video/sound format is the "standardized" one. 
And AFAIR, even an intel igp should be enough to get it to run at least in HD. 

Anyway, this was all but what I'd be expecting labeled as "audio issue". This is a hellish incubus. 
You'd need to analyze which audio format games is able to read, then hope somebody already made an encoder for it. 
(or I guess just straightway adding PS2 coded support to the game? U.u)
Kinda pretty bad that sh2fix was merged into WSF, when the widescreen part is just 10% by the end.

**Comment by AeroWidescreen** [comment]
> Kinda pretty bad that sh2fix was merged into WSF, when the widescreen part is just 10% by the end.

If you're talking about the widescreen fix then I'm not sure what you mean. A typical widescreen fix is made up of resolution, field of view, cutscene, full motion video, and menu modifications. It has all of the above, which makes up the majority of the code. 
The few non-widescreen related features that have been added were either requested bug fixes (LightingFix), compatibility fixes (SteamCrashFix), or enhancements (PS2CameraSpeed). I'm not sure why that's considered bad, or how any of this relates to the audio problems we're discussing.

**Comment by mirh** [comment]
I'm talking about [this](https://github.com/emoose/sh2proxy) going "inside" WSF rather than the other way around.

**Comment by elishacloud** [comment]
In Silent Hill 2 most of the audio files are stored in adx or afs.  This may also be the same format stored on the PS2 ISO (as this is a common PS2 format I believe).  As @mirh says it may be fairly easy to extract from the ISO.  I can look at this when I get some time in the next week or so.

However I recommend we take these final issues off this forum as these are not related to d3d8to9.  Can you repost them on [DxWrapper](https://github.com/elishacloud/dxwrapper)?

> You'd need to analyze which audio format games is able to read, then hope somebody already made an encoder for it.

Not necessarily.  Many games use winmm for audio playback.  If this game does that you can wrap winmm and use it to play just about any format you want.  Check out this [ogg-winmm](https://github.com/hifi-unmaintained/ogg-winmm) project for an example.

**Comment by AeroWidescreen** [comment]
@mirh I understand what you're saying. In hindsight I don't think it was the best choice either, but I'm not the one who ultimately makes those decisions. When it comes to adding other features, it's difficult because I want to please people with their requests, but I don't want to anger other people in the process. In the ideal world we could these mods together, like the fog fix or extra options, but that's not always possible. 😞 

@elishacloud Thanks for helping with this. I'll join you guys in the other forum and assist how ever I can.
